/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsSlugRouteImport } from './routes/workflows.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSlugRoute = WorkflowsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkflowsRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/workflows/$slug': typeof WorkflowsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/workflows/$slug': typeof WorkflowsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/workflows/$slug': typeof WorkflowsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/certifications'
    | '/contact'
    | '/experience'
    | '/faq'
    | '/gallery'
    | '/portfolio'
    | '/process'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/workflows'
    | '/portfolio/$slug'
    | '/workflows/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/certifications'
    | '/contact'
    | '/experience'
    | '/faq'
    | '/gallery'
    | '/portfolio'
    | '/process'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/workflows'
    | '/portfolio/$slug'
    | '/workflows/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/certifications'
    | '/contact'
    | '/experience'
    | '/faq'
    | '/gallery'
    | '/portfolio'
    | '/process'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/workflows'
    | '/portfolio/$slug'
    | '/workflows/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$slug': {
      id: '/workflows/$slug'
      path: '/$slug'
      fullPath: '/workflows/$slug'
      preLoaderRoute: typeof WorkflowsSlugRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface WorkflowsRouteChildren {
  WorkflowsSlugRoute: typeof WorkflowsSlugRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsSlugRoute: WorkflowsSlugRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
